# Generated by Django 5.2.1 on 2025-05-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=255)),
                ('shop_id', models.CharField(max_length=100)),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('visitor_id', 'shop_id')},
            },
        ),
    ]
